version: '3.7'
services:
   traefik:
      image: traefik:v1.7.16
      env_file:
         - ./server/.env.dev
      command: --api --docker --acme.email="hello@example.com"
      restart: always
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        - ./traefik/traefik.toml:/traefik.toml
        - ./traefik/acme.json:/acme.json
      ports:
        # Map port 80 and 443 on the host to this container.
        - "80:80"
        - "443:443"
      labels:
        - 'traefik.docker.network=frontend'
        - 'traefik.enable=true'
      #   - 'traefik.frontend.rule=Host:example.com,www.example.com; PathPrefixStrip:/traefik'
      #   - 'traefik.frontend.headers.STSSeconds=15768000'
      #   - 'traefik.frontend.auth.basic=admin:changeme'
        - 'traefik.port=8080'
        - 'traefik.protocol=http'
      networks:
      - backend
      - frontend

   postgresdb:
      image: postgres:alpine
      # depends_on:
      #    - traefik
      # *CHANGE THIS PASSWORD TO SOMETHING SECURE*
      environment:
        - POSTGRES_USER=admin
        - POSTGRES_PASSWORD=demo
        - POSTGRES_DB=reports
      restart: always
      ports:
        - 5432:5432
      networks:
         - backend


   server:
      container_name: express
      depends_on:
         - postgresdb
      env_file:
         - ./server/.env.dev
      restart: always
      build:
         context: ./server
         dockerfile: Dockerfile.dev
      volumes:
         - './server:/app'
         - /app/node_modules
      ports:
         - '5000:5000'
      networks:
         - backend

networks:
   frontend:
   backend:
