version: '3'
services:
   postgresdb:
      image: postgres:alpine
      # *CHANGE THIS PASSWORD TO SOMETHING SECURE*
      environment:
        - POSTGRES_USER=admin
        - POSTGRES_PASSWORD=demo
        - POSTGRES_DB=reports
      restart: always
      ports:
        - 5432:5432
      networks:
         my-network:
            ipv4_address: 172.16.0.13

   server:
      container_name: express
      depends_on:
         - postgresdb
      env_file:
         - ./server/.env.dev
      restart: always
      build:
         context: ./server
         dockerfile: Dockerfile.dev
      volumes:
         - './server:/app'
         - /app/node_modules
      ports:
         - '5000:5000'
      networks:
         my-network:
            ipv4_address: 172.16.0.12

networks:
   my-network:
      driver: bridge
      ipam:
         driver: default
         config:
            - subnet: 172.16.0.0/24
